[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/cancel.html"
  status = 200
